substitutions:
  wifi_fast_connect: "false"
  # connects to the first network the ESP sees, even if that network is very far
  # away and better ones are available.

packages: # These allow merging whereas global includes do not
  wifi: !include ../../secrets/wifi.yaml 

esphome:
  name: bed-light

esp8266:
  board: d1_mini

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: ""

captive_portal:

light:
- platform: neopixelbus
  type: GRB
  variant: WS2811
  pin: GPIO00
  num_leds: 89
  name: "Bed Light Joe"
  id: bed_light_joe
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    then:
      - light.turn_on:
          id: bed_light_joe
          red: 25%
          green: 25%
          blue: 50%
  effects:
    - addressable_rainbow:
        name: "Rainbow"
        speed: 10
        width: 5
    - addressable_color_wipe:
        name: "Color Wipe"
        colors:
          - red: 100%
            green: 0%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 100%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 0%
            blue: 100%
            num_leds: 89
    - addressable_twinkle:
        name: "Twinkle"
        twinkle_probability: 5%
    - addressable_fireworks:
        name: "Fireworks"
        update_interval: 32ms
        spark_probability: 10%
    - addressable_scan:
        name: "Scan"
        move_interval: 100ms
    - addressable_flicker:
        name: "Flicker"
        intensity: 25%

# Enable Home Assistant API
api:
  password: ""

