substitutions:
  wifi_fast_connect: "false"
  # connects to the first network the ESP sees, even if that network is very far
  # away and better ones are available.

packages: # These allow merging whereas global includes do not
  wifi: !include ../../secrets/wifi.yaml 

esphome:
  name: bed-light

esp8266:
  board: d1_mini

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: ""

captive_portal:

light:
- platform: neopixelbus
  id: bed_light_joe
  type: GRB
  variant: WS2811
  pin: GPIO04
  num_leds: 44
  name: "Bed Light Joe"
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    then:
      - light.turn_on:
          id: bed_light_joe
          red: 25%
          green: 25%
          blue: 50%

- platform: neopixelbus
  id: bed_light_steffi
  type: GRB
  variant: WS2811
  pin: GPIO05
  name: "Bed Light Steffi"
  num_leds: 44
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    then:
      - light.turn_on:
          id: bed_light_joe
          red: 25%
          green: 25%
          blue: 50%

# Enable Home Assistant API
api:
  password: ""

