substitutions:
  wifi_fast_connect: "false"
  # connects to the first network the ESP sees, even if that network is very far
  # away and better ones are available.

packages: # These allow merging whereas global includes do not
  wifi: !include ../../secrets/wifi.yaml 

esphome:
  name: terra
  
esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

i2c:
  # use default HW pins 
  # sda: 21 
  # scl: 22
  scan: false

dallas:
  - pin: D6

# sensors =====================================================
sensor:
  - platform: htu21d
    update_interval: 15s
    temperature:
      name: "TerraTemp"
      id: TerraTemp
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 60
    humidity:
      name: "TerraHumid"
      id: TerraHumid
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 60
  - platform: dallas
    address: 0xbb0317248403ff28
    name: "Soil Temperature"
    id: SoilTemp

# display and font stuff =====================================================
time:
  - platform: sntp
    id: thisTime

font:
  # gfonts://family[@weight]
  - file: "gfonts://Raleway@medium"
    id: ral_med_20
    size: 20
  - file: "gfonts://Raleway@medium"
    id: ral_med_15
    size: 15

# graph:
#   # Show bare-minimum auto-ranged graph
#   - id: tempGraph
#     sensor: TerraTemp
#     duration: 6h
#     width: 60
#     height: 40
#     x_grid: 2h
#     border: true
#   - id: humidGraph
#     sensor: TerraHumid
#     duration: 6h
#     width: 60
#     height: 40
#     x_grid: 2h
#     border: true

display:
  - platform: ssd1306_i2c
    id: the_display
    model: "SH1106 128x64"
    address: 0x3C # default is 0x3C
    update_interval: 30s # don't make too high or WIFI will be affected...
    pages:
    - id: page1
      lambda: |-
        it.strftime(0, 0, id(ral_med_15), "%Y-%m-%d", id(thisTime).now());
        it.strftime(0, 16, id(ral_med_15), "%H:%M", id(thisTime).now());
        it.printf(64, 20, id(ral_med_20), "%.1f C", id(SoilTemp).raw_state);
        it.printf(0, 40, id(ral_med_20), "%.1f C", id(TerraTemp).raw_state);
        it.printf(64, 40, id(ral_med_20), "%.1f %%", id(TerraHumid).raw_state);

# Example configuration entry
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2813
    pin: D5
    num_leds: 120
    name: "NeoPixel Light"