substitutions:
  wifi_fast_connect: "false"
  # connects to the first network the ESP sees, even if that network is very far
  # away and better ones are available.

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

esphome:
  name: coffee-light-shared

esp8266:
  board: d1_mini

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: ""

light:
- platform: neopixelbus
  type: GRB
  variant: 800KBPS
  pin: GPIO00 #D3
  num_leds: 89
  name: "Coffee Light Shared"
  id: coffee_light_shared
  effects:
    - addressable_rainbow:
        name: "Rainbow"
        speed: 15
        width: 10
    - addressable_color_wipe:
        name: "Color Wipe"
        colors:
          - red: 100%
            green: 0%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 100%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 0%
            blue: 100%
            num_leds: 89
    - addressable_twinkle:
        name: "Twinkle"
        twinkle_probability: 15%
    - addressable_fireworks:
        name: "Fireworks"
        update_interval: 32ms
        spark_probability: 20%
    - addressable_scan:
        name: "Scan"
        move_interval: 75ms
    - addressable_flicker:
        name: "Flicker"
        intensity: 50%

# Enable Home Assistant API
api:
  password: ""

