substitutions:
  wifi_fast_connect: "false"
  # connects to the first network the ESP sees, even if that network is very far
  # away and better ones are available.

packages: # These allow merging whereas global includes do not
  wifi: !include ../../secrets/wifi.yaml 

esphome:
  name: coffee-light

esp8266:
  board: d1_mini

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: ""

captive_portal:

light:
- platform: neopixelbus
  type: GRB
  variant: WS2811
  pin: GPIO00
  num_leds: 89
  name: "Coffee Light"
  id: coffee_light
  restore_mode: RESTORE_DEFAULT_ON
  on_turn_on:
    then:
      - light.turn_on:
          id: coffee_light
          red: 25%
          green: 25%
          blue: 50%
  effects:
    - addressable_rainbow:
        name: "Rainbow"
        speed: 10
        width: 5
    - addressable_color_wipe:
        name: "Color Wipe"
        colors:
          - red: 100%
            green: 0%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 100%
            blue: 0%
            num_leds: 89
          - red: 0%
            green: 0%
            blue: 100%
            num_leds: 89
    - addressable_twinkle:
        name: "Twinkle"
        twinkle_probability: 5%
    - addressable_fireworks:
        name: "Fireworks"
        update_interval: 32ms
        spark_probability: 10%
    - addressable_scan:
        name: "Scan"
        move_interval: 100ms
    - addressable_flicker:
        name: "Flicker"
        intensity: 25%

- platform: partition
  name: "Coffee Light C"
  segments:
    - id: coffee_light
      from: 0
      to: 8
    - id: coffee_light
      from: 79
      to: 88

- platform: partition
  name: "Coffee Light o"
  segments:
    - id: coffee_light
      from: 10
      to: 14
    - id: coffee_light
      from: 73
      to: 77

- platform: partition
  name: "Coffee Light f1"
  segments:
    - id: coffee_light
      from: 15
      to: 21
    - id: coffee_light
      from: 66
      to: 71

- platform: partition
  name: "Coffee Light f2"
  segments:
    - id: coffee_light
      from: 22
      to: 28
    - id: coffee_light
      from: 59
      to: 64

- platform: partition
  name: "Coffee Light e1"
  segments:
    - id: coffee_light
      from: 29
      to: 32
    - id: coffee_light
      from: 48
      to: 57

- platform: partition
  name: "Coffee Light e2"
  segments:
    - id: coffee_light
      from: 34
      to: 47

# Enable Home Assistant API
api:
  password: ""

